const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { promisify } = require('node:util');
const { Pool } = require('pg');

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required.');
const scrypt = promisify(crypto.scrypt);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 10 });
const publicDir = path.join(__dirname, 'mindmitra-nepal-complete-html');
const port = Number(process.env.PORT || 3000);
const cookieName = 'mindmitra_session';
const sessionMs = 7 * 24 * 60 * 60 * 1000;
const attempts = new Map();
const mime = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml' };

function send(res,status,payload,headers={}) { res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}); res.end(JSON.stringify(payload)); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(part=>{const i=part.indexOf('=');return [part.slice(0,i).trim(),decodeURIComponent(part.slice(i+1))]})); }
async function readBody(req) { let raw=''; for await(const chunk of req){raw+=chunk;if(raw.length>1_000_000)throw Object.assign(new Error('Request is too large.'),{status:413})} if(!raw)return{};try{return JSON.parse(raw)}catch{throw Object.assign(new Error('Invalid JSON request.'),{status:400})} }
function required(value,label,max=5000){const text=String(value||'').trim();if(!text)throw Object.assign(new Error(`${label} is required.`),{status:400});if(text.length>max)throw Object.assign(new Error(`${label} is too long.`),{status:400});return text}
async function makePasswordHash(password){const salt=crypto.randomBytes(16);const hash=await scrypt(password,salt,64);return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`}
async function verifyPassword(password,stored){const [kind,saltHex,hashHex]=String(stored||'').split('$');if(kind!=='scrypt'||!saltHex||!hashHex)return false;const expected=Buffer.from(hashHex,'hex');const actual=await scrypt(password,Buffer.from(saltHex,'hex'),expected.length);return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}
function safeUser(u){return{id:u.id,email:u.email,full_name:u.full_name,role:u.role,organization_id:u.organization_id,username:u.username,member_type:u.member_type,department:u.department,first_login:u.first_login,is_active:u.is_active}}
async function newSession(userId,res){const token=crypto.randomBytes(32).toString('base64url');const hash=crypto.createHash('sha256').update(token).digest('hex');await pool.query('insert into user_sessions(token_hash,user_id,expires_at) values($1,$2,$3)',[hash,userId,new Date(Date.now()+sessionMs)]);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`${cookieName}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${sessionMs/1000}${secure}`)}
async function renewSession(req,res){const token=parseCookies(req)[cookieName];if(!token)return;const hash=crypto.createHash('sha256').update(token).digest('hex');await pool.query('update user_sessions set expires_at=$2 where token_hash=$1',[hash,new Date(Date.now()+sessionMs)]);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`${cookieName}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${sessionMs/1000}${secure}`)}
async function currentUser(req){const token=parseCookies(req)[cookieName];if(!token)return null;const hash=crypto.createHash('sha256').update(token).digest('hex');const result=await pool.query('select u.* from user_sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now() and u.is_active=true',[hash]);return result.rows[0]||null}
function assessmentReport(data){const scores={};for(const answer of Array.isArray(data.answers)?data.answers:[]){const value=Number(answer.value||0),score=answer.reverse_scored?3-value:value;scores[answer.domain]=(scores[answer.domain]||0)+score}const concerns=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([domain,score])=>({domain,score}));const total=Number(data.total_score||0),risk=total>=66?'urgent':total>=41?'elevated':total>=21?'moderate':'low',lifestyle=data.lifestyle||{},suggestions=[];if(Number(lifestyle.sleep_hours)>0&&Number(lifestyle.sleep_hours)<7)suggestions.push('Aim for a consistent sleep routine and reduce screen use before bedtime.');if(['Never','Rarely'].includes(lifestyle.exercise_frequency))suggestions.push('Add a short walk or gentle movement several times each week.');if(['High','Very High'].includes(lifestyle.caffeine_intake))suggestions.push('Consider reducing caffeine, particularly later in the day.');suggestions.push('Use a short breathing, grounding, or journaling practice when stress rises.');if(risk==='moderate'||risk==='elevated'||risk==='urgent')suggestions.push('Consider booking a confidential appointment with a verified counsellor.');const message=risk==='low'?'Your responses suggest that you are generally managing well right now.':risk==='moderate'?'Your responses suggest mild but meaningful stress. Regular self-care and check-ins may help.':risk==='elevated'?'Your responses suggest ongoing concerns that could benefit from support from a counsellor.':'Your responses indicate a high level of concern. Please contact a verified counsellor or a trusted support person soon.';return {risk,message,summary:message,main_concerns:concerns.map(x=>x.domain),domain_scores:scores,suggestions,disclaimer:'This automated wellbeing report is not a medical diagnosis or emergency service.'}}
async function requireUser(req,roles){const user=await currentUser(req);if(!user)throw Object.assign(new Error('Please sign in again.'),{status:401});if(roles&&!roles.includes(user.role))throw Object.assign(new Error('You are not authorized for this action.'),{status:403});return user}

async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/health'){await pool.query('select 1');return send(res,200,{ok:true,database:'neon-postgresql'})}
  if(req.method==='POST'&&url.pathname==='/api/auth/register'){
    const d=await readBody(req),email=required(d.email,'Email',320).toLowerCase(),password=String(d.password||''),fullName=required(d.full_name,'Full name',200),role=['counsellor','organization_admin'].includes(d.role)?d.role:null;
    if(!role)throw Object.assign(new Error('This account type cannot be self-registered.'),{status:400});if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error('Enter a valid email address.'),{status:400});if(password.length<8)throw Object.assign(new Error('Password must have at least 8 characters.'),{status:400});
    const client=await pool.connect();try{await client.query('begin');let orgId=null;if(role==='organization_admin'){const org=await client.query('insert into organizations(name,organization_type) values($1,$2) returning id',[fullName,d.organization_type||null]);orgId=org.rows[0].id}const hash=await makePasswordHash(password);const result=await client.query('insert into users(email,password_hash,full_name,role,organization_id) values($1,$2,$3,$4,$5) returning *',[email,hash,fullName,role,orgId]);const user=result.rows[0];await client.query('insert into notification_preferences(user_id) values($1)',[user.id]);if(role==='counsellor')await client.query('insert into counsellor_profiles(user_id,phone,licence_number,address_line,city,province,latitude,longitude,whatsapp_enabled) values($1,$2,$3,$4,$5,$6,$7,$8,$9)',[user.id,d.phone||null,d.licence_number||null,d.address_line||null,d.city||null,d.province||null,d.latitude||null,d.longitude||null,Boolean(d.phone)]);await client.query('commit');await newSession(user.id,res);return send(res,201,{user:safeUser(user)})}catch(e){await client.query('rollback');if(e.code==='23505')throw Object.assign(new Error('An account with that email already exists.'),{status:409});throw e}finally{client.release()}
  }
  if(req.method==='POST'&&url.pathname==='/api/auth/login'){
    const key=req.socket.remoteAddress||'unknown',state=attempts.get(key)||{count:0,reset:Date.now()+60000};if(Date.now()>state.reset){state.count=0;state.reset=Date.now()+60000}if(state.count>=10)throw Object.assign(new Error('Too many login attempts. Try again in one minute.'),{status:429});const d=await readBody(req),login=required(d.email,'Email or username',320).toLowerCase();const result=await pool.query('select u.*,o.organization_type from users u left join organizations o on o.id=u.organization_id where lower(u.email)=lower($1) or lower(u.username)=lower($1) limit 1',[login]);const user=result.rows[0];if(!user||!(await verifyPassword(String(d.password||''),user.password_hash))){state.count++;attempts.set(key,state);throw Object.assign(new Error('The email or password is incorrect.'),{status:401})}if(!user.is_active)throw Object.assign(new Error('This account has been deactivated.'),{status:403});if(d.role&&user.role!==d.role)throw Object.assign(new Error(`This account belongs to the ${user.role.replaceAll('_',' ')} portal.`),{status:403});if(user.role==='organization_admin'&&String(d.organization_type||'').trim().toLowerCase()!==String(user.organization_type||'').trim().toLowerCase())throw Object.assign(new Error('The organization type does not match this account.'),{status:403});attempts.delete(key);await newSession(user.id,res);return send(res,200,{user:safeUser(user)})
  }
  if(req.method==='GET'&&url.pathname==='/api/auth/me'){const user=await currentUser(req);if(!user)return send(res,200,{user:null,privacy:null});await renewSession(req,res);const privacy=user.role==='client'?(await pool.query('select * from privacy_preferences where user_id=$1',[user.id])).rows[0]||null:null;return send(res,200,{user:safeUser(user),privacy})}
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const token=parseCookies(req)[cookieName];if(token)await pool.query('delete from user_sessions where token_hash=$1',[crypto.createHash('sha256').update(token).digest('hex')]);res.setHeader('Set-Cookie',`${cookieName}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`);return send(res,200,{ok:true})}
  if(req.method==='GET'&&url.pathname==='/api/counsellors'){
    const lat=Number(url.searchParams.get('lat')),lng=Number(url.searchParams.get('lng')),radius=Math.min(Number(url.searchParams.get('radius')||250),500),located=Number.isFinite(lat)&&Number.isFinite(lng);const result=await pool.query(`select cp.*,u.full_name${located?`,6371*2*asin(sqrt(power(sin(radians(cp.latitude-$1)/2),2)+cos(radians($1))*cos(radians(cp.latitude))*power(sin(radians(cp.longitude-$2)/2),2))) distance_km`:''} from counsellor_profiles cp join users u on u.id=cp.user_id where cp.verification_status='approved' and u.is_active=true ${located?'and cp.latitude is not null and cp.longitude is not null order by distance_km':'order by u.full_name'}`,located?[lat,lng]:[]);const rows=located?result.rows.filter(x=>Number(x.distance_km)<=radius):result.rows;return send(res,200,{counsellors:rows.map(({phone,...x})=>({...x,whatsapp_link:x.whatsapp_enabled&&phone?`https://wa.me/${String(phone).replace(/\D/g,'')}`:null,distance_km:x.distance_km==null?null:Number(x.distance_km)}))})
  }
  if(req.method==='POST'&&url.pathname==='/api/contact'){const d=await readBody(req);await pool.query('insert into contact_messages(name,email,topic,message) values($1,$2,$3,$4)',[required(d.name,'Name',200),required(d.email,'Email',320),required(d.topic,'Topic',200),required(d.message,'Message')]);return send(res,201,{ok:true})}
  if(req.method==='PUT'&&url.pathname==='/api/privacy'){const user=await requireUser(req,['client']),d=await readBody(req),share=Boolean(d.share_identity_with_counsellor),alias=share?(d.anonymous_alias||null):required(d.anonymous_alias,'Anonymous alias',100);await pool.query("insert into privacy_preferences(user_id,share_identity_with_counsellor,anonymous_alias,updated_at) values($1,$2,$3,now()) on conflict(user_id) do update set share_identity_with_counsellor=excluded.share_identity_with_counsellor,anonymous_alias=excluded.anonymous_alias,updated_at=now()",[user.id,share,alias]);return send(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/assessments'){
    const user=await requireUser(req,['client']),d=await readBody(req),score=Number(d.total_score||0),summary=assessmentReport(d),risk=summary.risk,client=await pool.connect();try{await client.query('begin');const session=await client.query("insert into assessment_sessions(user_id,answers,lifestyle,total_score,result_level,completed_at) values($1,$2,$3,$4,$5,now()) returning id",[user.id,JSON.stringify(d.answers||[]),JSON.stringify(d.lifestyle||{}),score,d.result_level||null]);const report=await client.query('insert into ai_reports(session_id,user_id,user_summary,risk_level,urgent_human_review) values($1,$2,$3,$4,$5) returning id,user_summary,risk_level,created_at',[session.rows[0].id,user.id,JSON.stringify(summary),risk,risk==='urgent']);await client.query('commit');return send(res,201,{session_id:session.rows[0].id,report:report.rows[0]})}catch(e){await client.query('rollback');throw e}finally{client.release()}
  }
  if(req.method==='GET'&&url.pathname==='/api/reports'){const user=await requireUser(req,['client']);const reports=await pool.query('select r.id,r.user_summary,r.risk_level,r.created_at,s.total_score,s.result_level from ai_reports r join assessment_sessions s on s.id=r.session_id where r.user_id=$1 order by r.created_at desc',[user.id]);return send(res,200,{reports:reports.rows})}
  if(req.method==='GET'&&url.pathname==='/api/appointments'){const user=await requireUser(req,['client','counsellor']);if(user.role==='client'){const rows=await pool.query("select a.*,u.full_name counsellor_name,cp.whatsapp_enabled,cp.phone from appointments a join users u on u.id=a.counsellor_id join counsellor_profiles cp on cp.user_id=a.counsellor_id where a.client_id=$1 order by a.created_at desc",[user.id]);return send(res,200,{appointments:rows.rows.map(({phone,...a})=>({...a,whatsapp_link:a.status==='confirmed'&&a.whatsapp_enabled&&phone?`https://wa.me/${String(phone).replace(/\D/g,'')}`:null}))})}const rows=await pool.query("select a.*,u.full_name client_name,r.user_summary,r.risk_level from appointments a join users u on u.id=a.client_id left join lateral (select user_summary,risk_level from ai_reports where user_id=a.client_id and consent_to_share=true order by created_at desc limit 1) r on true where a.counsellor_id=$1 order by a.created_at desc",[user.id]);return send(res,200,{appointments:rows.rows})}
  if(req.method==='POST'&&url.pathname==='/api/appointments'){const user=await requireUser(req,['client']),d=await readBody(req),counsellor=await pool.query("select cp.user_id from counsellor_profiles cp join users u on u.id=cp.user_id where cp.user_id=$1 and cp.verification_status='approved' and u.is_active=true",[required(d.counsellor_id,'Counsellor')]);if(!counsellor.rowCount)throw Object.assign(new Error('This counsellor is not available for booking.'),{status:400});const client=await pool.connect();try{await client.query('begin');const appointment=await client.query("insert into appointments(client_id,counsellor_id,status) values($1,$2,'requested') returning *",[user.id,d.counsellor_id]);if(d.share_report)await client.query('update ai_reports set consent_to_share=true where id=(select id from ai_reports where user_id=$1 order by created_at desc limit 1)',[user.id]);await client.query('commit');return send(res,201,{appointment:appointment.rows[0]})}catch(e){await client.query('rollback');throw e}finally{client.release()}}
  if(req.method==='PATCH'&&url.pathname.startsWith('/api/appointments/')){const user=await requireUser(req,['client','counsellor']),id=url.pathname.split('/').pop(),d=await readBody(req);if(user.role==='counsellor'&&d.action==='approve'){const result=await pool.query("update appointments set status='approved' where id=$1 and counsellor_id=$2 and status='requested' returning *",[id,user.id]);if(!result.rowCount)throw Object.assign(new Error('This request is no longer available to approve.'),{status:400});return send(res,200,{appointment:result.rows[0]})}if(user.role==='client'&&d.action==='confirm'){const result=await pool.query("update appointments set status='confirmed' where id=$1 and client_id=$2 and status='approved' returning *",[id,user.id]);if(!result.rowCount)throw Object.assign(new Error('This appointment must be approved before you confirm it.'),{status:400});return send(res,200,{appointment:result.rows[0]})}throw Object.assign(new Error('This appointment action is not allowed.'),{status:403})}
  if(req.method==='GET'&&url.pathname==='/api/organization/dashboard'){
    const user=await requireUser(req,['organization_admin']);if(!user.organization_id)throw Object.assign(new Error('Organization information is missing for this account.'),{status:400});const id=user.organization_id,[summary,risks,monthly]=await Promise.all([pool.query("select count(*) filter(where member_type='student')::int total_students,count(*) filter(where member_type='employee')::int total_employees,(select count(*)::int from assessment_sessions a join users x on x.id=a.user_id where x.organization_id=$1) total_assessments,(select count(*)::int from ai_reports r join users x on x.id=r.user_id where x.organization_id=$1 and r.risk_level='urgent') urgent_cases,(select count(*)::int from appointments a join users x on x.id=a.client_id where x.organization_id=$1 and a.scheduled_at>now()) upcoming_appointments,(select count(*)::int from appointments a join users x on x.id=a.client_id where x.organization_id=$1 and a.status='completed') completed_appointments from users where organization_id=$1",[id]),pool.query('select r.risk_level,count(*)::int total from ai_reports r join users u on u.id=r.user_id where u.organization_id=$1 group by r.risk_level order by r.risk_level',[id]),pool.query("select date_trunc('month',a.completed_at) as \"month\",count(*)::int assessments from assessment_sessions a join users u on u.id=a.user_id where u.organization_id=$1 group by 1 order by 1",[id])]);return send(res,200,{summary:summary.rows[0],risk_distribution:risks.rows,monthly_assessments:monthly.rows})
  }
  if(req.method==='POST'&&url.pathname==='/api/organization/users'){
    const admin=await requireUser(req,['organization_admin']),d=await readBody(req),password=String(d.temporary_password||'');if(!admin.organization_id)throw Object.assign(new Error('Admin is not linked to an organization.'),{status:400});if(password.length<8)throw Object.assign(new Error('Temporary password must have at least 8 characters.'),{status:400});const client=await pool.connect();try{await client.query('begin');const result=await client.query("insert into users(email,password_hash,full_name,role,organization_id,username,member_type,department,first_login) values($1,$2,$3,'client',$4,$5,$6,$7,true) returning id,email",[required(d.email,'Email',320).toLowerCase(),await makePasswordHash(password),required(d.full_name,'Full name',200),admin.organization_id,required(d.username,'Username',100),d.member_type,d.department||null]);const created=result.rows[0],alias=`Mitra-${created.id.replaceAll('-','').slice(0,6).toUpperCase()}`;await client.query('insert into privacy_preferences(user_id,share_identity_with_counsellor,anonymous_alias) values($1,$2,$3)',[created.id,!d.allow_anonymous_counselling,alias]);await client.query('insert into notification_preferences(user_id) values($1)',[created.id]);await client.query("insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values($1,'organization_user_created','user',$2,$3)",[admin.id,created.id,JSON.stringify({username:d.username,member_type:d.member_type})]);await client.query('commit');return send(res,201,{success:true,user_id:created.id,email:created.email})}catch(e){await client.query('rollback');if(e.code==='23505')throw Object.assign(new Error('That email or username is already registered.'),{status:409});throw e}finally{client.release()}
  }
  if(req.method==='POST'&&url.pathname==='/api/counsellor/notes'){const user=await requireUser(req,['counsellor']),d=await readBody(req);await pool.query('insert into counsellor_notes(counsellor_id,appointment_id,client_id,private_note) values($1,$2,$3,$4)',[user.id,d.appointment_id||null,d.client_id||null,required(d.private_note,'Private note')]);return send(res,201,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/counsellor/reports'){const user=await requireUser(req,['counsellor']),d=await readBody(req);if(!d.client_consent_confirmed)throw Object.assign(new Error('Client consent must be confirmed.'),{status:400});await pool.query("insert into organization_reports(counsellor_id,organization_id,appointment_id,client_id,client_display_name,report_summary,client_consent_confirmed,status,published_at) values($1,$2,$3,$4,$5,$6,true,'published',now())",[user.id,d.organization_id||null,d.appointment_id||null,d.client_id||null,d.client_display_name||'Anonymous Client',required(d.report_summary,'Report')]);return send(res,201,{ok:true})}
  if(req.method==='GET'&&url.pathname.startsWith('/api/appointments/')){const user=await requireUser(req),id=url.pathname.split('/').pop(),result=await pool.query('select * from appointments where id=$1 and (client_id=$2 or counsellor_id=$2)',[id,user.id]);if(!result.rowCount)throw Object.assign(new Error('Appointment not found.'),{status:404});return send(res,200,{appointment:result.rows[0]})}
  if(req.method==='POST'&&url.pathname==='/api/feedback'){const user=await requireUser(req,['client']),d=await readBody(req),result=await pool.query("select * from appointments where id=$1 and client_id=$2 and status='completed'",[d.appointment_id,user.id]);if(!result.rowCount)throw Object.assign(new Error('Feedback is allowed only for your completed appointment.'),{status:403});const a=result.rows[0];await pool.query('insert into appointment_feedback(appointment_id,client_id,counsellor_id,rating,felt_listened_to,helpful_session,easy_to_join,recommend_counsellor,feedback) values($1,$2,$3,$4,$5,$6,$7,$8,$9)',[a.id,user.id,a.counsellor_id,d.rating,d.felt_listened_to,d.helpful_session,d.easy_to_join,d.recommend_counsellor,d.feedback||null]);return send(res,201,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/counsellor/followups'){const user=await requireUser(req,['counsellor']),d=await readBody(req),result=await pool.query('select client_id from appointments where id=$1 and counsellor_id=$2',[d.appointment_id,user.id]);if(!result.rowCount)throw Object.assign(new Error('Appointment not found.'),{status:404});await pool.query("insert into counsellor_followup_emails(counsellor_id,client_id,appointment_id,message) values($1,$2,$3,$4) on conflict(appointment_id) do update set message=excluded.message,status='queued'",[user.id,result.rows[0].client_id,d.appointment_id,required(d.message,'Message')]);return send(res,202,{ok:true,status:'queued'})}
  return send(res,404,{error:'API route not found.'});
}

async function staticFile(res,url){let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';const file=path.resolve(publicDir,`.${pathname}`);if(!file.startsWith(publicDir+path.sep))return send(res,403,{error:'Forbidden.'});try{const stat=await fs.promises.stat(file),resolved=stat.isDirectory()?path.join(file,'index.html'):file,extension=path.extname(resolved).toLowerCase();res.writeHead(200,{'Content-Type':mime[extension]||'application/octet-stream','Cache-Control':['.html','.js'].includes(extension)?'no-cache':'public, max-age=86400'});res.end(await fs.promises.readFile(resolved))}catch{send(res,404,{error:'File not found.'})}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(url.pathname.startsWith('/api/'))await api(req,res,url);else await staticFile(res,url)}catch(error){console.error(error);send(res,error.status||500,{error:error.status?error.message:'Server error.'})}});
server.listen(port,()=>console.log(`MindMitra Neon server running at http://localhost:${port}`));
async function shutdown(){server.close();await pool.end()}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
